Ecommerce_p/Ecommerce_P/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shopping_app.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce_p/Shopping_app/urls.py
from django.urls import path
from . import views
app_name = 'Shopping_app'


urlpatterns = [

    path('',views.All_Cat,name='All_Cat'),
    path('<slug:c_slug>',views.All_Cat,name='products_by_ category'),
    path('<slug:c_slug>/<slug:p_slug>', views.All_product, name='products'),

]

Ecommerce_p/cartapp/urls.py
from django.urls import path
from . import views
app_name = 'cartapp'


urlpatterns = [

    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),


]

Ecommerce_p/search_app/urls.py
from django.urls import path
from . import views
app_name = 'search_app'


urlpatterns = [

    path('',views.Search,name='search'),


]

Ecommerce_p/Shopping_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    des = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('Shopping_app:products_by_ category', args=[self.slug])


    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    des = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('Shopping_app:products', args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'


    def __str__(self):
        return '{}'.format(self.name)

Ecommerce_p/cartapp/models.py
from django.db import models
from Shopping_app.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return'{}'.format (self.cart_id)

class Cart_item(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='Cart_item'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format (self.product)

Ecommerce_p/search_app/models.py
from django.db import models

# Create your models here.

Ecommerce_p/Shopping_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,InvalidPage,EmptyPage

# Create your views here.
def All_Cat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products' : products})


def All_product(request,c_slug,p_slug):

    try:
        product=Product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

Ecommerce_p/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Shopping_app.models import Product
from .models import Cart,Cart_item
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except    Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=Cart_item.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
                cart_item.quantity += 1
        cart_item.save()
    except Cart_item.DoesNotExist :
        cart_item=Cart_item.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cartapp:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=Cart_item.objects.filter(cart=cart,active=True)
        for i in cart_items:
            total += (i.product.price * i.quantity)
            counter += i.quantity
    except ObjectDoesNotExist:
        pass

    return render(request,'cart.html',dict(total=total,counter = counter,cart_items=cart_items))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=Cart_item.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cart_item.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

Ecommerce_p/search_app/views.py
from django.shortcuts import render
from Shopping_app.models import Product
from django.db.models import Q
# Create your views here.

def Search(request):
    query=None
    products=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(des__contains=query))
    return render(request,'search.html',{'query': query ,'products': products})

Ecommerce_p/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

   <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>

       <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}<br>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
    </div>
</body>
</html>

Ecommerce_p/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   This is the CART page
{% endblock %}
{% block title %}
   YOUR CART
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">
        YOUR SHOPPING CART IS EMPTY
    </h1>
    <br>
    <p class="text-center">
      PLEASE CLICK<a href="{% url 'Shopping_app:All_Cat' %}">here</a>to continue your shopping.
    </p>


  </div>
</div>
{% else %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">
      YOUR SHOPPING CART
    </h1>
    <br>

  </div>

  <div class="row mx_auto">
     <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
           <thead class="my_custom_thead">
            <tr>

                <th colspan="6">
                    Your Items
                </th>
            </tr>
           </thead>
           <tbody>
           {% for cart_item in cart_items %}
           <tr>
             <td>
                <a href="#"><img src="{{cart_item.product.img.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
             </td>
             <td class="text-left">
                {{cart_item.product.name}}
                <br>
                SKU: {{cart_item.product.id}}
                <br>
                Price ${{cart_item.product.price}}
                <br>
                Quantity : {{cart_item.quantity}} $ {{cart_item}}

             </td>
             <td>
                $ {{cart_item.sub_total}}
             </td>
             {% if cart_item.quantity < cart_item.product.stock %}
             <td>
                 <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus-circle custom_icon"></i></a>
                 &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-circle custom_icon" ></i></a>
                 &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon" ></i></a>
             </td>
             {% else %}
             <td>
                 &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-circle custom_icon" ></i></a>
                 &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon" ></i></a>
             </td>
           </tr>
             {% endif %}
             {% endfor %}
             </tbody>
        </table>
     </div>


     <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="6">
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
            <tr>
              <td>
                  Please Review Your Cart Items before placing the order..
              </td>
            </tr>
            <tr>
                <td class="text-left">
                    YOUR TOTAL IS : <strong>{{ total }}</strong>

                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
              <a href="{% url 'Shopping_app:All_Cat' %}" class="btn btn-secondary btn btn-block my_custom-button">Continue Shopping....</a>
              <a href="{% url 'Shopping_app:All_Cat' %}" class="btn btn-secondary btn btn-block my_custom-button">Make Payments</a>
        </div>
     </div>
  </div>
</div>
{% endif %}
{% endblock %}

Ecommerce_p/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{category.des|truncatewords:155}}
  {% else %}
     welcome to ABC store where you can buy different things......
  {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
      {{category.name}}----> ABC store
   {% else %}
       Our new collections....
   {% endif %}
{% endblock %}

{% block content %}
   {% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx_auto">
        <p><a href="{% url 'Shopping_app:All_Cat' %}">Our Product Collections.</a></p>
        </div>
    </div>
</div>
   {% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}" width="1500px" height="1500px">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}} </h1><br>
    <p class="text-justify">{{category.des}}</p>
</div>
   {% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products" width="1300px">
    </div>
<br>
<div>
    <h1 class="text-center my_title">our product collections</h1>
    <p class="text-justify">What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>

</div>
   {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for i in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4" >
            <div class="card text-center" style="width:20rem; height:25rem;" >
                <a href="{{i.get_url}}" ><img class="card-img-top my_image" src="{{i.img.url}}" alt="{{i.name}}"  width="150px" height="150px"></a>
                <div class="card-body" style="width:20rem;"  >
                    <h4 class="card-title">{{i.name}}</h4>
                    <p class="card-text">${{i.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages  > 1 %}
        <hr>
        <div class="text-center">
            {% for i in products.paginator.page_range %}
            <a href="?page={{i}}" class="btn btn-info {% if products.number == i %} active {% endif %}">{{i}}</a>
            {% endfor %}
        </div>
        {% endif %}

    </div>
    <br>
</div>
{% endblock %}

Ecommerce_p/templates/footer.html
{% load static %}
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">
      &copy; ABC Planet tech pvt ltd.
    </p>
</div>

Ecommerce_p/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'Shopping_app:All_Cat' %}"><img src="{% static 'img/logo.png' %}" alt="logo image" width="150px"></a>


  </center>
</header>

Ecommerce_p/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Shopping_app:All_Cat' %}">Home</a>
        </li>

        <li class="nav-item dropdown {% if 'Shopping_app' in request.path %} active {% endif %} ">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <b>SHOP</b>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Shopping_app:All_Cat' %}">ALL PRODUCTS</a></li>
            <li><hr class="dropdown-divider"></li>
             {% for i in links %}
            <li><a class="dropdown-item" href="{{ i.get_url }}">{{i.name}}</a></li>
             {% endfor %}


          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:search' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

Ecommerce_p/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.des|truncatewords:155}}

{% endblock %}
{% block title %}

      {{product.name}}- ABC store


{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
  <div class="mx_auto">
    <p><a href="{% url 'Shopping_app:All_Cat' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
  </div>
</div>
<div class="container">
<br>
<div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <div style="min-width:18rem">
           <img src="{{product.img.url}}" alt="{{product.name}}" style="width:300px;height:300px;">
    </div>
  </div>


  <div class="col-12 col-sm-12 col-md-12 col-lg-6">

    <h1 class="my_prod_title">{{product.name}}</h1>
    <p>${{product.price}}</p>
    <p class="my_title">PRODUCT DESCRIPTION</p>
    <p class="text-justify my_prod_text">{{product.des}}</p>
    {% if product.stock <= 0 %}
    <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
    {% else %}
    <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}">ADD TO CART</a>
    {% endif %}
  </div>

  </div>
  </div>

{% endblock %}

Ecommerce_p/templates/rough.html
<link href="{% static 'css/custom.css' %}" rel="stylesheet">
     <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

     <script src="https://kit.fontawesome.com/a076d05399.js"></script>
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

Ecommerce_p/templates/search.html
{% extends 'base.html' %}

{% load static %}
{% block metadescription %}

    We have variety of products.

{% endblock %}
{% block title %}

    search result

{% endblock %}
{% block content %}

<div>
    <p class="text-center search_text "> you have searched for : <b>{{query}}</b></p>

</div>
<div class="row mx_auto">
        {% for i in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4" >
            <div class="card text-center" style="width:18rem">
                <a href="{{i.get_url}}" ><img class="card-img-top my_image" src="{{i.img.url}}" alt="{{i.name}}" width="150px"></a>
                <div class="card-body">
                    <h4 class="card-title">{{i.name}}</h4>
                    <p class="card-text">${{i.price}}</p>
                </div>
            </div>
             </div>




    {% empty %}
    <div class="mx_auto">
           <p class="text-center search_text"> 0 results found.</p>

       </div>
   {% endfor %}
    </div>

</div>



{% endblock %}